export type SalesRow = { month: string; meetings: number; visits: number; units: number; area: number }

export const demoSalesRows: SalesRow[] = [
  { month: 'Apr', meetings: 298, visits: 1, units: 0, area: 0 }, { month: 'May', meetings: 348, visits: 10, units: 0, area: 0 }, { month: 'Jun', meetings: 404, visits: 19, units: 9, area: 8860 }, { month: 'Jul', meetings: 283, visits: 14, units: 7, area: 10162 }, { month: 'Aug', meetings: 406, visits: 19, units: 17, area: 15003 },
]

const clean = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, '')
function csvRows(text: string) { const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false; for (const char of text) { if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(cell); cell = '' } else if ((char === '\n' || char === '\r') && !quoted) { if (cell || row.length) { row.push(cell); rows.push(row); row = []; cell = '' } } else cell += char } if (cell || row.length) rows.push([...row, cell]); return rows }
export function toCsvUrl(source: string) { if (source.includes('export?format=csv') || source.includes('gviz/tq')) return source; const id = source.match(/\/d\/([\w-]+)/)?.[1]; const gid = source.match(/[?&#]gid=(\d+)/)?.[1] ?? '0'; return id ? `https://docs.google.com/spreadsheets/d/${id}/export?format=csv&gid=${gid}` : source }
export async function loadSalesRows(source: string): Promise<SalesRow[]> { const csvUrl = toCsvUrl(source); const response = await fetch(`${csvUrl}${csvUrl.includes('?') ? '&' : '?'}_=${Date.now()}`); if (!response.ok) throw new Error('The Google Sheet could not be loaded.'); const [header, ...rawRows] = csvRows(await response.text()); if (!header) throw new Error('The sheet needs a header row.'); const columns = header.map(clean); const get = (row: string[], aliases: string[]) => row[columns.findIndex((column) => aliases.includes(column))] ?? ''; const numeric = (value: string) => Number(value.replace(/,/g, '')) || 0; const rows = rawRows.map((row) => ({ month: get(row, ['month', 'period']), meetings: numeric(get(row, ['cpmeetings', 'meetings'])), visits: numeric(get(row, ['totalvisits', 'visits'])), units: numeric(get(row, ['eoiunits', 'units'])), area: numeric(get(row, ['eoiarea', 'area'])) })).filter((row) => row.month); if (!rows.length) throw new Error('No valid sales records were found.'); return rows }
