import { useEffect, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { RefreshCw, Settings2 } from 'lucide-react'
import { demoSalesRows, type SalesRow } from './lib/sales-data'
import './App.css'

const n = new Intl.NumberFormat('en-IN')
const cards: { label: string; key: keyof Omit<SalesRow, 'month'>; unit?: string }[] = [{ label: 'CP Meetings', key: 'meetings' }, { label: 'Total Visits', key: 'visits' }, { label: 'EOI Units', key: 'units' }, { label: 'EOI Area', key: 'area', unit: 'sq ft' }]

export default function App() {
  const [rows, setRows] = useState<SalesRow[]>(demoSalesRows); const [live, setLive] = useState(false); const [status, setStatus] = useState('Connecting to your secure data source…')
  const refresh = async () => { try { const response = await fetch('/api/sales', { cache: 'no-store' }); if (!response.ok) throw new Error(); const data = await response.json() as { rows: SalesRow[] }; if (!data.rows.length) throw new Error(); setRows(data.rows); setLive(true); setStatus(`Private Google Sheet · refreshed ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`) } catch { setLive(false); setStatus('Secure data source is not configured yet — demo data shown.') } }
  useEffect(() => { refresh(); const timer = setInterval(refresh, 60000); return () => clearInterval(timer) }, [])
  const current = rows.at(-1) ?? demoSalesRows.at(-1)!; const previous = rows.at(-2) ?? current; const data = rows.map((row) => ({ ...row, areaK: +(row.area / 1000).toFixed(1) })); const margin = { top: 18, right: 12, left: -16, bottom: 0 }
  return <main className="dashboard"><header className="hero"><h1><em>Amber</em> — {current.month} 2026 Sales Report</h1><p>Performance summary · {current.month} 2026</p></header><div className="toolbar"><span><i className={live ? 'lamp live' : 'lamp'} />{status}</span><div><button onClick={() => refresh()}><RefreshCw size={15} />Refresh</button><span className="private"><Settings2 size={15} />Private connection</span></div></div><section className="metrics">{cards.map((card) => { const value = current[card.key], old = previous[card.key], delta = old ? (value - old) / old * 100 : 0; return <article className="metric" key={card.key}><p>{card.label}</p><strong>{n.format(value)} {card.unit && <small>{card.unit}</small>}</strong><div><span className={delta < 0 ? 'negative' : ''}>{delta < 0 ? '▼' : '▲'} {Math.abs(delta).toFixed(2)}%</span><em>vs {n.format(old)} ({previous.month})</em></div></article>})}</section><h2 className="section-title">Monthly Trends</h2><section className="charts"><article><h3>CP Meetings</h3><ResponsiveContainer width="100%" height={235}><LineChart data={data} margin={margin}><CartesianGrid vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line dataKey="meetings" stroke="#43297c" strokeWidth={3} /></LineChart></ResponsiveContainer></article><article><h3>Total Visits</h3><ResponsiveContainer width="100%" height={235}><LineChart data={data} margin={margin}><CartesianGrid vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line dataKey="visits" stroke="#43297c" strokeWidth={3} /></LineChart></ResponsiveContainer></article><article><h3>EOI</h3><ResponsiveContainer width="100%" height={235}><BarChart data={data} margin={margin}><CartesianGrid vertical={false} /><XAxis dataKey="month" /><YAxis yAxisId="units" /><YAxis yAxisId="area" orientation="right" tickFormatter={(v) => `${v}k`} /><Tooltip /><Bar yAxisId="units" dataKey="units" fill="#43297c" radius={[4,4,0,0]} /><Bar yAxisId="area" dataKey="areaK" fill="#c8b27f" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer><p className="legend"><span>● EOI Units</span><span>● EOI Area (sq ft)</span></p></article></section><footer className="brand">Superb Realty · Sales &amp; Marketing Analytics</footer></main>
}
